# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blackjack < Formula
  desc "Fortio terminal blackjack card game"
  homepage "https://fortio.org/"
  version "0.53.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/terminal/releases/download/v0.53.1/blackjack_0.53.1_darwin_amd64.zip"
      sha256 "9a2c0c3cf9ce1146dac39d142b9336423897402cd8c8e3a8fe4ab4e0dac784a8"

      def install
        bin.install "blackjack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/terminal/releases/download/v0.53.1/blackjack_0.53.1_darwin_arm64.zip"
      sha256 "b6862b5a5f9192919076360bbe4f890de8f0aab68e29c439a9ca1427654dc1d6"

      def install
        bin.install "blackjack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/terminal/releases/download/v0.53.1/blackjack_0.53.1_linux_amd64.tar.gz"
      sha256 "a84c439fa946e02e9d5655f1676730c93745ca61aad44f7299e80d1461602282"
      def install
        bin.install "blackjack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/terminal/releases/download/v0.53.1/blackjack_0.53.1_linux_arm64.tar.gz"
      sha256 "9088afb169971e253d0739a8446448a430297052445054f7bb88f97ad67286f5"
      def install
        bin.install "blackjack"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/blackjack -version")
  end
end
