# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blackjack < Formula
  desc "Fortio terminal blackjack card game"
  homepage "https://fortio.org/"
  version "0.52.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/terminal/releases/download/v0.52.1/blackjack_0.52.1_darwin_amd64.zip"
      sha256 "e9e92fd74f12faf3ecfd06f84fcbb076bfc67edb8e23c9ee833ab24560247a1c"

      def install
        bin.install "blackjack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/terminal/releases/download/v0.52.1/blackjack_0.52.1_darwin_arm64.zip"
      sha256 "4f71b93f1bb6c04da88fad44b71274f7ba27e4a752676358e3f9ce58ef4431be"

      def install
        bin.install "blackjack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/terminal/releases/download/v0.52.1/blackjack_0.52.1_linux_amd64.tar.gz"
      sha256 "2228d599cbd636cf0cc61cdb8ed6c257054602fa18c7279588c225daf7beb711"
      def install
        bin.install "blackjack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/terminal/releases/download/v0.52.1/blackjack_0.52.1_linux_arm64.tar.gz"
      sha256 "4146035739c7d2356a8d4acb7d40dff568a45b86e4b4688ff1db699b9da758a7"
      def install
        bin.install "blackjack"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/blackjack -version")
  end
end
