# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brick < Formula
  desc "Fortio terminal brick smashing game in the style of Breakout"
  homepage "https://fortio.org/"
  version "0.39.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/terminal/releases/download/v0.39.1/brick_0.39.1_darwin_amd64.zip"
      sha256 "98886844f80fcec485879f64f4465e72100d278f5379dab4fb4767bbca55e8f0"

      def install
        bin.install "brick"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/terminal/releases/download/v0.39.1/brick_0.39.1_darwin_arm64.zip"
      sha256 "141d44d938fb0256add66ea5c62995e02e171f2def00f3af8f438310f74b2850"

      def install
        bin.install "brick"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/terminal/releases/download/v0.39.1/brick_0.39.1_linux_amd64.tar.gz"
      sha256 "db7a6307559efb74bd88c9c4eb0938090db15a1e6968823e259fd0498abab137"
      def install
        bin.install "brick"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/terminal/releases/download/v0.39.1/brick_0.39.1_linux_arm64.tar.gz"
      sha256 "3e20201abc9b81480f324c9ef8ec7fffc1ef525f477c84fb3b9a4e2375232a8e"
      def install
        bin.install "brick"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/brick -version")
  end
end
