# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Delta < Formula
  desc "Fortio + open telemetry tracing"
  homepage "https://fortio.org/"
  version "1.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/delta/releases/download/v1.0.4/delta_1.0.4_darwin_amd64.tar.gz"
      sha256 "9cbcefc1f8d7cd5ab1a6229a8dc059417a562a64f9e39989bd781d85e30f9929"

      def install
        bin.install "delta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/delta/releases/download/v1.0.4/delta_1.0.4_darwin_arm64.tar.gz"
      sha256 "b2e8613dfc3ffabfc17478991c6358893ff39b29063a3f9208984cf28cf86d66"

      def install
        bin.install "delta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/delta/releases/download/v1.0.4/delta_1.0.4_linux_arm64.tar.gz"
      sha256 "6d870032d7e2a786da2d67e36cf2cfdc37c68a514e7085a17198fd9e9cf95f4d"

      def install
        bin.install "delta"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fortio/delta/releases/download/v1.0.4/delta_1.0.4_linux_amd64.tar.gz"
      sha256 "b15af5a2354015e5b269dbde073b576d62eb86c764089b49fe90c212c0d861aa"

      def install
        bin.install "delta"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/delta -version")
  end
end
