# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Delta < Formula
  desc "Fortio delta tool"
  homepage "https://fortio.org/"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fortio/delta/releases/download/v1.1.0/delta_1.1.0_darwin_arm64.tar.gz"
      sha256 "a55359d6e995c54f3253429f11507c91c3d14182fbb36ef8f8c5d78cfbdf998f"

      def install
        bin.install "delta"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fortio/delta/releases/download/v1.1.0/delta_1.1.0_darwin_amd64.tar.gz"
      sha256 "bc61e86026593b1933005338a76b9664e55dd8a99ee599e327c8b8baceefde8f"

      def install
        bin.install "delta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/delta/releases/download/v1.1.0/delta_1.1.0_linux_arm64.tar.gz"
      sha256 "baad6a0d29435eed0978a6d71f18982e9b9b12ecaf1e2467c22f5aae6b143d36"

      def install
        bin.install "delta"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fortio/delta/releases/download/v1.1.0/delta_1.1.0_linux_amd64.tar.gz"
      sha256 "8c73901a38574614b1e4588ffbe1a4132a8f0715a40c5a8f02040c49cd93cc9b"

      def install
        bin.install "delta"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/delta -version")
  end
end
