# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demo < Formula
  desc "Support for high dynamic range synthetic PNG image in go"
  homepage "https://fortio.org/"
  version "0.1.0-pre1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/hdr/releases/download/v0.1.0-pre1/demo_0.1.0-pre1_darwin_amd64.zip"
      sha256 "e8075cb55beb10747a81645b3aeb1b2cb218301d1e13924825793cdf20191cd0"

      define_method(:install) do
        bin.install "demo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/hdr/releases/download/v0.1.0-pre1/demo_0.1.0-pre1_darwin_arm64.zip"
      sha256 "ba0830e1f7e01b901ab92535bd4eb79612fc249fb49dc2fc4b074626a8606c92"

      define_method(:install) do
        bin.install "demo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/hdr/releases/download/v0.1.0-pre1/demo_0.1.0-pre1_linux_amd64.tar.gz"
      sha256 "05c43db61045a135fbe87711d9c42b802028590a6f633dd5ab832394782e12b0"
      define_method(:install) do
        bin.install "demo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/hdr/releases/download/v0.1.0-pre1/demo_0.1.0-pre1_linux_arm64.tar.gz"
      sha256 "62940ff42f8fa44c30d2173df909a419ca9912bc622e9df559738e31db499ebc"
      define_method(:install) do
        bin.install "demo"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/demo -version")
  end
end
