# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demo < Formula
  desc "Support for high dynamic range synthetic PNG image in go"
  homepage "https://fortio.org/"
  version "0.1.0-pre2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/hdr/releases/download/v0.1.0-pre2/demo_0.1.0-pre2_darwin_amd64.zip"
      sha256 "b5f7b3a71bbeacc0924f58cbae3ed4054d3c7164d299673188472729cf009aae"

      define_method(:install) do
        bin.install "demo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/hdr/releases/download/v0.1.0-pre2/demo_0.1.0-pre2_darwin_arm64.zip"
      sha256 "e7d6c9df4daab105286de478ab1f4e18e831fe1d9304956ed36bcc63051840ac"

      define_method(:install) do
        bin.install "demo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/hdr/releases/download/v0.1.0-pre2/demo_0.1.0-pre2_linux_amd64.tar.gz"
      sha256 "0bcf5555bf080ce3b448d08bff1907b1cab90527d62d8eb0a385136772ce07c2"
      define_method(:install) do
        bin.install "demo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/hdr/releases/download/v0.1.0-pre2/demo_0.1.0-pre2_linux_arm64.tar.gz"
      sha256 "1b4b54761a7b135d3ef3f4dae54590751ca1299db62d3ce82e492e204d6ff1c3"
      define_method(:install) do
        bin.install "demo"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/demo -version")
  end
end
