# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fortiotel < Formula
  desc "Fortio + open telemetry tracing"
  homepage "https://fortio.org/"
  version "1.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fortio/fortiotel/releases/download/v1.1.2/fortiotel_1.1.2_Mac_arm64.tar.gz"
      sha256 "a2f04636079a22a8ca268afc45ffef6bf4d37e089524c4f85fa01162ce876b08"

      def install
        bin.install "fortiotel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fortio/fortiotel/releases/download/v1.1.2/fortiotel_1.1.2_Mac_x86_64.tar.gz"
      sha256 "973077960a739c855fd9f9fe05df86f29a09c236ddb0a9f982d54a8e5e9b8e62"

      def install
        bin.install "fortiotel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/fortiotel/releases/download/v1.1.2/fortiotel_1.1.2_Linux_arm64.tar.gz"
      sha256 "b5bb5650c0eb41bf1ef81ae16f61b82d89d3f4e472674c0f9a42bfa8589ecd83"

      def install
        bin.install "fortiotel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fortio/fortiotel/releases/download/v1.1.2/fortiotel_1.1.2_Linux_x86_64.tar.gz"
      sha256 "ec36d1c4184a216244c033744fbebe85e800114f77c64b8943f52390f1e6f3c7"

      def install
        bin.install "fortiotel"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fortiotel -version")
  end
end
