# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fortiotel < Formula
  desc "Fortio + open telemetry tracing"
  homepage "https://fortio.org/"
  version "1.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fortio/fortiotel/releases/download/v1.2.1/fortiotel_1.2.1_Mac_arm64.tar.gz"
      sha256 "14ca431acd86fe169ebc651d3537f949bafc99b2ef32a702e66e022e055b36f9"

      def install
        bin.install "fortiotel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fortio/fortiotel/releases/download/v1.2.1/fortiotel_1.2.1_Mac_x86_64.tar.gz"
      sha256 "54aea11a70badb7f61b637b0ae13b8da6f5b26c7a358a059f6cb9d1464294a79"

      def install
        bin.install "fortiotel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/fortiotel/releases/download/v1.2.1/fortiotel_1.2.1_Linux_x86_64.tar.gz"
      sha256 "588c400f7e82915cce4644643da2aa8a78bf9bddfd95e79cef4526bc3b8928f9"

      def install
        bin.install "fortiotel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/fortiotel/releases/download/v1.2.1/fortiotel_1.2.1_Linux_arm64.tar.gz"
      sha256 "575d0331b0d302a9091a3cf47d582323ffc2fbfe603f984ff2807e6798d39b70"

      def install
        bin.install "fortiotel"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fortiotel -version")
  end
end
