# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fps < Formula
  desc "Fortio terminal fps checker"
  homepage "https://fortio.org/"
  version "0.52.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/fps/releases/download/v0.52.2/fps_0.52.2_darwin_amd64.zip"
      sha256 "f161fe1d87dabc4789511f4dfe16e5641f467f853f7da982d3cb2e6e2a9d9120"

      def install
        bin.install "fps"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/fps/releases/download/v0.52.2/fps_0.52.2_darwin_arm64.zip"
      sha256 "503ef0c5705db66f97d2dc87370be3d9ef21343b697ea3bcf690deb524ada9a8"

      def install
        bin.install "fps"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/fps/releases/download/v0.52.2/fps_0.52.2_linux_amd64.tar.gz"
      sha256 "ab99e9730e15266530318fe21915bcd1f846a7e38936d9e30ac362a22fcb11cb"
      def install
        bin.install "fps"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/fps/releases/download/v0.52.2/fps_0.52.2_linux_arm64.tar.gz"
      sha256 "e1d121c0e7187bf515e2a2008966670a1854a6ca2d2ddc21bbae64f6a1d6749f"
      def install
        bin.install "fps"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fps -version")
  end
end
