# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fps < Formula
  desc "Fortio terminal fps checker"
  homepage "https://fortio.org/"
  version "0.63.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/fps/releases/download/v0.63.3/fps_0.63.3_darwin_amd64.zip"
      sha256 "cba6f4116d72e4af55ee6ba53063532c2a25afdb516a90af4417a179d7d425c5"

      def install
        bin.install "fps"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/fps/releases/download/v0.63.3/fps_0.63.3_darwin_arm64.zip"
      sha256 "aff54d5bca9d19c1a38170db640c5097acef30231dad3f9cbf5d91d1adbb89e0"

      def install
        bin.install "fps"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/fps/releases/download/v0.63.3/fps_0.63.3_linux_amd64.tar.gz"
      sha256 "a53db67b8c7aa404a6e60f650dbbf74f0b67639c5fb40fdb133602ae900a117c"
      def install
        bin.install "fps"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/fps/releases/download/v0.63.3/fps_0.63.3_linux_arm64.tar.gz"
      sha256 "424f88c6fdd75314c623de667cad13ee2aa75ab39881db418a3311135f93ab81"
      def install
        bin.install "fps"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fps -version")
  end
end
