# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fps < Formula
  desc "Fortio terminal fps checker"
  homepage "https://fortio.org/"
  version "0.60.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/fps/releases/download/v0.60.1/fps_0.60.1_darwin_amd64.zip"
      sha256 "737eeb2cedf3ce7399fb5e17c701162086ef36969024185b2164db9d0a0bcd4d"

      def install
        bin.install "fps"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/fps/releases/download/v0.60.1/fps_0.60.1_darwin_arm64.zip"
      sha256 "d10365f2fbde05e2ec5b8fc1935d5888284c1a38ebc906e9accbaa386cc478f5"

      def install
        bin.install "fps"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/fps/releases/download/v0.60.1/fps_0.60.1_linux_amd64.tar.gz"
      sha256 "7a077330571604a7d383eb433e2caad2bb918b126b89a4877857af88adc00e5b"
      def install
        bin.install "fps"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/fps/releases/download/v0.60.1/fps_0.60.1_linux_arm64.tar.gz"
      sha256 "c8f3fb760964e430414e04b9ed46800631bce2c97c090955946ffdceb8d66077"
      def install
        bin.install "fps"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fps -version")
  end
end
