# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gvi < Formula
  desc "Fortio terminal vi like editor"
  homepage "https://fortio.org/"
  version "0.8.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/gvi/releases/download/v0.8.1/gvi_0.8.1_darwin_amd64.zip"
      sha256 "7b2b9dd86d97d2fa28a1962afa85c094200c4d4183b430129cea7f752df52e3f"

      def install
        bin.install "gvi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/gvi/releases/download/v0.8.1/gvi_0.8.1_darwin_arm64.zip"
      sha256 "5c645c5d5be4dd053c7e8e6c8c7fdf8624d7254f3db6abeef91adf101e199101"

      def install
        bin.install "gvi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/gvi/releases/download/v0.8.1/gvi_0.8.1_linux_amd64.tar.gz"
      sha256 "60221ff52e55854a34cdf83eb00a4cf1875faafa1f0450f7b6a4b74e864b360a"
      def install
        bin.install "gvi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/gvi/releases/download/v0.8.1/gvi_0.8.1_linux_arm64.tar.gz"
      sha256 "eb7b193f44e91e3ceb60959baff6db672411568cd59a6db3b91a76c5163eaaa7"
      def install
        bin.install "gvi"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gvi -version")
  end
end
