# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gvi < Formula
  desc "Fortio terminal vi like editor"
  homepage "https://fortio.org/"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/gvi/releases/download/v0.7.0/gvi_0.7.0_darwin_amd64.zip"
      sha256 "4346bf93a5bb943315dcb96c1abc52e548703045099f5dc358080ca8af9f0631"

      def install
        bin.install "gvi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/gvi/releases/download/v0.7.0/gvi_0.7.0_darwin_arm64.zip"
      sha256 "ca3fd91a8108cf77080d69dfd98b0f6213b42a90eae4092625114c8a3581b6c9"

      def install
        bin.install "gvi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/gvi/releases/download/v0.7.0/gvi_0.7.0_linux_amd64.tar.gz"
      sha256 "443316c14f3cb023b8bcb5e6ba855fdfd7250604a8c2f9181a522bc9f066b9a8"
      def install
        bin.install "gvi"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/gvi/releases/download/v0.7.0/gvi_0.7.0_linux_arm64.tar.gz"
      sha256 "a44062849f491a312c88248bdef35c244cd8b2703006ec9edd51601c1ebce984"
      def install
        bin.install "gvi"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gvi -version")
  end
end
