# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gvi < Formula
  desc "Fortio terminal vi like editor"
  homepage "https://fortio.org/"
  version "0.8.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/gvi/releases/download/v0.8.4/gvi_0.8.4_darwin_amd64.zip"
      sha256 "8fd5378a9c71bfcc9021b4bee4c13c538ed9ca94aa1321655fb4e5de456ea0df"

      define_method(:install) do
        bin.install "gvi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/gvi/releases/download/v0.8.4/gvi_0.8.4_darwin_arm64.zip"
      sha256 "ff637ecfd396653767bd0bd774879de13f2f418f4fa972519bb53890a03da0ec"

      define_method(:install) do
        bin.install "gvi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/gvi/releases/download/v0.8.4/gvi_0.8.4_linux_amd64.tar.gz"
      sha256 "41c3774aa4d3cd0c49e4fa9e45254e403a7a4e5efe0aed9f414b075fb83c93e0"
      define_method(:install) do
        bin.install "gvi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/gvi/releases/download/v0.8.4/gvi_0.8.4_linux_arm64.tar.gz"
      sha256 "4da8acfc39b5c4cec99789e82a613cfe5fd9869480f75c5bd55e242b46b38514"
      define_method(:install) do
        bin.install "gvi"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gvi -version")
  end
end
