# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class H2cli < Formula
  desc "Simple http 2.0 (h2 and h2c) client in go, including streaming"
  homepage "https://fortio.org/"
  version "1.3.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/h2cli/releases/download/v1.3.2/h2cli_1.3.2_darwin_amd64.zip"
      sha256 "6547fc8c122edb8d5c590991c8669c3afcc428acdef9d82585b50dcef3f06d79"

      define_method(:install) do
        bin.install "h2cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/h2cli/releases/download/v1.3.2/h2cli_1.3.2_darwin_arm64.zip"
      sha256 "5dff84b7c8ec283b7be9cb4484acd37ed67a10d590cb319e02fd08940d916da0"

      define_method(:install) do
        bin.install "h2cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/h2cli/releases/download/v1.3.2/h2cli_1.3.2_linux_amd64.tar.gz"
      sha256 "11edb9d657705fb897d96d376b7b4b5f07482cefe11bb5de160efc393a6a14f9"
      define_method(:install) do
        bin.install "h2cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/h2cli/releases/download/v1.3.2/h2cli_1.3.2_linux_arm64.tar.gz"
      sha256 "40c05e54f41f0eac0aa1cc30defd99e698fd77b98b0877155eb4191744bbf963"
      define_method(:install) do
        bin.install "h2cli"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/h2cli -version")
  end
end
