# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class H2cli < Formula
  desc "Simple http 2.0 (h2 and h2c) client in go, including streaming"
  homepage "https://fortio.org/"
  version "1.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/h2cli/releases/download/v1.3.1/h2cli_1.3.1_darwin_amd64.zip"
      sha256 "2163eb0708da2ecd0a1e5c868f6b53b86ccb29ae4ee791919213def95f2d2527"

      define_method(:install) do
        bin.install "h2cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/h2cli/releases/download/v1.3.1/h2cli_1.3.1_darwin_arm64.zip"
      sha256 "34f9558f6dfaedeb8eedb4034d60eab3f73256d309a3dc15a36edb627f8ad971"

      define_method(:install) do
        bin.install "h2cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/h2cli/releases/download/v1.3.1/h2cli_1.3.1_linux_amd64.tar.gz"
      sha256 "8cc646941424327efc5dc840af186ac4ac2b37ae31ba8a07577ca41281f8e40f"
      define_method(:install) do
        bin.install "h2cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/h2cli/releases/download/v1.3.1/h2cli_1.3.1_linux_arm64.tar.gz"
      sha256 "d805e3bc80813d39eaafd46ad4bef40c9b2c63f49ea5e226a5a39223647a44f3"
      define_method(:install) do
        bin.install "h2cli"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/h2cli -version")
  end
end
