# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class H2life < Formula
  desc "Fortio ansipixels to http - life game demo"
  homepage "https://fortio.org/"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/h2life/releases/download/v0.4.1/h2life_0.4.1_darwin_amd64.zip"
      sha256 "eea1c01da544c0d11c9fd76d7ace03d35dc0b4c165fa67bdf21b65315cdb075b"

      def install
        bin.install "h2life"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/h2life/releases/download/v0.4.1/h2life_0.4.1_darwin_arm64.zip"
      sha256 "abe4d043f11c752d89d93230e54576e67e7eab2729e2725901e2481a20f1be28"

      def install
        bin.install "h2life"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/h2life/releases/download/v0.4.1/h2life_0.4.1_linux_amd64.tar.gz"
        sha256 "4642e9f9ee6c6847b10871d907bf921cf90076dd52533740c5869648f5369955"

        def install
          bin.install "h2life"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/h2life/releases/download/v0.4.1/h2life_0.4.1_linux_arm64.tar.gz"
        sha256 "1d6b72cf6ca29561eae39e114d6cfb7067c25e6da5afd8250507fc3396731057"

        def install
          bin.install "h2life"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/h2life -version")
  end
end
