# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class H2life < Formula
  desc "Fortio ansipixels to http - life game demo"
  homepage "https://fortio.org/"
  version "0.10.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/h2life/releases/download/v0.10.3/h2life_0.10.3_darwin_amd64.zip"
      sha256 "25185db9f8899d270322c064c3c6b7d2a29457cb53f509bba452a8363cca032f"

      def install
        bin.install "h2life"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/h2life/releases/download/v0.10.3/h2life_0.10.3_darwin_arm64.zip"
      sha256 "8ef369eac57f0e8bea84c277d0f78b545309e325f8d2717b73f954c0ffcfd3de"

      def install
        bin.install "h2life"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/h2life/releases/download/v0.10.3/h2life_0.10.3_linux_amd64.tar.gz"
      sha256 "21167a43957c9070c07e4ae20bdc1334b27f9ecac3557832c1945e5fe7ff687e"
      def install
        bin.install "h2life"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/h2life/releases/download/v0.10.3/h2life_0.10.3_linux_arm64.tar.gz"
      sha256 "91f65e484d9bcc45675e203bd95c9a4eaf27468e589770264109a48d81a45a19"
      def install
        bin.install "h2life"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/h2life -version")
  end
end
