# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HdrDemo < Formula
  desc "Support for high dynamic range synthetic PNG image in go"
  homepage "https://fortio.org/"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/hdr/releases/download/v1.1.0/hdr_demo_1.1.0_darwin_amd64.zip"
      sha256 "b99b8a81ae2c6435b501f665a825c740076e356d7f515e099f8251583624b4b8"

      define_method(:install) do
        bin.install "hdr_demo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/hdr/releases/download/v1.1.0/hdr_demo_1.1.0_darwin_arm64.zip"
      sha256 "777ebaf9e3249184af307713ded61717c45377f80b77f6b05c3b825424e1fd27"

      define_method(:install) do
        bin.install "hdr_demo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/hdr/releases/download/v1.1.0/hdr_demo_1.1.0_linux_amd64.tar.gz"
      sha256 "a299b5d66b711c382bb08300843560b8ede3537b9f8c9da132a38340c8226498"
      define_method(:install) do
        bin.install "hdr_demo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/hdr/releases/download/v1.1.0/hdr_demo_1.1.0_linux_arm64.tar.gz"
      sha256 "90f5fbf1af21b72792e8e8c1cdeb296301930a1b296236f3488480fea39bb395"
      define_method(:install) do
        bin.install "hdr_demo"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hdr_demo -version")
  end
end
