# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HdrDemo < Formula
  desc "Support for high dynamic range synthetic PNG image in go"
  homepage "https://fortio.org/"
  version "0.2.0-pre1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/hdr/releases/download/v0.2.0-pre1/hdr_demo_0.2.0-pre1_darwin_amd64.zip"
      sha256 "f5dc7461823fb0cfeb80b1af2d2209ea07992c6062561e609e96764e5a412996"

      define_method(:install) do
        bin.install "hdr_demo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/hdr/releases/download/v0.2.0-pre1/hdr_demo_0.2.0-pre1_darwin_arm64.zip"
      sha256 "369c3c590d303bde5a9162a1be2fb389e4d2629c82dc2b359ed33620158b69c9"

      define_method(:install) do
        bin.install "hdr_demo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/hdr/releases/download/v0.2.0-pre1/hdr_demo_0.2.0-pre1_linux_amd64.tar.gz"
      sha256 "90be83f55d770e2e6242ab593d72d93110cdb688c003f3c64e9636fe1dbe5e0f"
      define_method(:install) do
        bin.install "hdr_demo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/hdr/releases/download/v0.2.0-pre1/hdr_demo_0.2.0-pre1_linux_arm64.tar.gz"
      sha256 "02e6fb18e78c48a4fcdc712249295cfe81fe7e542f92946d74d8e23df4d77868"
      define_method(:install) do
        bin.install "hdr_demo"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hdr_demo -version")
  end
end
