# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HdrDemo < Formula
  desc "Support for high dynamic range synthetic PNG image in go"
  homepage "https://fortio.org/"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/hdr/releases/download/v1.0.0/hdr_demo_1.0.0_darwin_amd64.zip"
      sha256 "92e9aa2fb2a22c63d5396fd7ea1df935836b28fd4d7ce36379bdd4de29aa5630"

      define_method(:install) do
        bin.install "hdr_demo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/hdr/releases/download/v1.0.0/hdr_demo_1.0.0_darwin_arm64.zip"
      sha256 "23bba2e1cf89a5f4b15c7a1f5555466ce942c6ab3834aaad79fc7049eb26f72e"

      define_method(:install) do
        bin.install "hdr_demo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/hdr/releases/download/v1.0.0/hdr_demo_1.0.0_linux_amd64.tar.gz"
      sha256 "258977b5955b8e6908f65f1f2e03bb04297770fdc6a685f41560477418724815"
      define_method(:install) do
        bin.install "hdr_demo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/hdr/releases/download/v1.0.0/hdr_demo_1.0.0_linux_arm64.tar.gz"
      sha256 "87fbceaf12e8daf9af60848093b72500d448a5263a417b18bd1611f589895127"
      define_method(:install) do
        bin.install "hdr_demo"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hdr_demo -version")
  end
end
