# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Life < Formula
  desc "Fortio terminal Conway's game of life demo"
  homepage "https://fortio.org/"
  version "0.25.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/fortio/terminal/releases/download/v0.25.0/life_0.25.0_darwin_amd64.zip"
      sha256 "77b825eff1af16f80e9909b947e4aff709df076d44cb45fa3c447d55daabf839"

      def install
        bin.install "life"
      end
    end
    on_arm do
      url "https://github.com/fortio/terminal/releases/download/v0.25.0/life_0.25.0_darwin_arm64.zip"
      sha256 "0125ee5e9cdda44d45cd28e102f5ec4284dffb344cf1bfc2319df82ec0344e59"

      def install
        bin.install "life"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/terminal/releases/download/v0.25.0/life_0.25.0_linux_amd64.tar.gz"
        sha256 "bb35c97e7fd0bf29d80339c274393c0f814027ce8ddff3c9bdfc781aaa56a6fd"

        def install
          bin.install "life"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/terminal/releases/download/v0.25.0/life_0.25.0_linux_arm64.tar.gz"
        sha256 "e5041260328d8a07261a60298002a9b6d41d3e893efe0ef0d7583a2cd49f3a5e"

        def install
          bin.install "life"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/life -version")
  end
end
