# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Life < Formula
  desc "Fortio terminal Conway's game of life demo"
  homepage "https://fortio.org/"
  version "0.57.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/terminal/releases/download/v0.57.1/life_0.57.1_darwin_amd64.zip"
      sha256 "96c68a5bff698fe4f86db5a935fd423232b32acba9f77b84597496cf8d6f11aa"

      def install
        bin.install "life"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/terminal/releases/download/v0.57.1/life_0.57.1_darwin_arm64.zip"
      sha256 "76d331fa724d77f150aec0ff5e7f79dd60bc1fb306b367af66cf54efa32e47a2"

      def install
        bin.install "life"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/terminal/releases/download/v0.57.1/life_0.57.1_linux_amd64.tar.gz"
      sha256 "ce772c303fedf49b10594ffb0ab284018523f118e78a9023820284a0086258e5"
      def install
        bin.install "life"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/terminal/releases/download/v0.57.1/life_0.57.1_linux_arm64.tar.gz"
      sha256 "5d40f460044b2c419d6c9adaeba437184a6c9b716f780fb209c7c43f3dc91f88"
      def install
        bin.install "life"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/life -version")
  end
end
