# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LllFixer < Formula
  desc "Fix line too long lll linter errors"
  homepage "https://fortio.org/"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ldemailly/lll-fixer/releases/download/v0.1.0/lll-fixer_0.1.0_darwin_arm64.tar.gz"
      sha256 "5a991e6ce042e1c7d3be080f5da0be5f7b8c9e1097142aa6af92a15d0c3be887"

      def install
        bin.install "lll-fixer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ldemailly/lll-fixer/releases/download/v0.1.0/lll-fixer_0.1.0_darwin_amd64.tar.gz"
      sha256 "69a97e8b09cce1b0505378fe5083f0f2871e97a38bb3bea3e481ae5632fe3438"

      def install
        bin.install "lll-fixer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ldemailly/lll-fixer/releases/download/v0.1.0/lll-fixer_0.1.0_linux_arm64.tar.gz"
      sha256 "35ed239aeb2ca3967c5ea6ec46968a530922f922f663d7578270df24deeaaca9"

      def install
        bin.install "lll-fixer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ldemailly/lll-fixer/releases/download/v0.1.0/lll-fixer_0.1.0_linux_amd64.tar.gz"
      sha256 "0c1cc9301410bb6d98041a6a97cf9c1c5629e181a69353d2591d24e915b4acbd"

      def install
        bin.install "lll-fixer"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lll-fixer -version")
  end
end
