# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LllFixer < Formula
  desc "Fix line too long lll linter errors"
  homepage "https://fortio.org/"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ldemailly/lll-fixer/releases/download/v0.1.1/lll-fixer_0.1.1_darwin_amd64.tar.gz"
      sha256 "d5b48a5a8a4a032cb563fd7ea3ba0d6af8f7c363785f8b2dd461ab7d1b6f9daf"

      def install
        bin.install "lll-fixer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ldemailly/lll-fixer/releases/download/v0.1.1/lll-fixer_0.1.1_darwin_arm64.tar.gz"
      sha256 "c5812cf410ea009f59756f89d586a0b5ab57c8dd321ef9666a9d4a4a070e1a18"

      def install
        bin.install "lll-fixer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ldemailly/lll-fixer/releases/download/v0.1.1/lll-fixer_0.1.1_linux_arm64.tar.gz"
      sha256 "344c8ab84fd62470b7738ce7924753dbfadbfe2f8563b29d2e587b0637db75b0"

      def install
        bin.install "lll-fixer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ldemailly/lll-fixer/releases/download/v0.1.1/lll-fixer_0.1.1_linux_amd64.tar.gz"
      sha256 "cdb70e46a8c5098bdf9cde5df9d8954911869637ed8564e6c02a865b27ea609b"

      def install
        bin.install "lll-fixer"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lll-fixer -version")
  end
end
