# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logc < Formula
  desc "Fortio log JSON to (colorized) text converter"
  homepage "https://fortio.org/"
  version "1.3.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/logc/releases/download/v1.3.3/logc_1.3.3_darwin_amd64.tar.gz"
      sha256 "2a92bdb9e59b53033c7398c55dedcd4c86d9baf0f8293a9e04cda78886736ef7"

      def install
        bin.install "logc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/logc/releases/download/v1.3.3/logc_1.3.3_darwin_arm64.tar.gz"
      sha256 "98341927468a37f2ee1a79d4b95bc49fe45a978ea69f934846482bb12290c06c"

      def install
        bin.install "logc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/logc/releases/download/v1.3.3/logc_1.3.3_linux_arm64.tar.gz"
      sha256 "c171feb13e781b484a130fe7c3009089e398cbe09381292707fc9de131c65fa3"

      def install
        bin.install "logc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fortio/logc/releases/download/v1.3.3/logc_1.3.3_linux_amd64.tar.gz"
      sha256 "eac142b46f7c607401c33cb5cb55da0b44e55c029cd9e5bb82e8f7a35ccad742"

      def install
        bin.install "logc"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/logc -version")
  end
end
