# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logc < Formula
  desc "Fortio log JSON to (colorized) text converter"
  homepage "https://fortio.org/"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fortio/logc/releases/download/v1.0.0/logc_1.0.0_darwin_arm64.tar.gz"
      sha256 "4f302b627676a9dc0d925796dcb7f439ffed6f538b3c493928c72e25c07a755a"

      def install
        bin.install "logc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fortio/logc/releases/download/v1.0.0/logc_1.0.0_darwin_amd64.tar.gz"
      sha256 "3da4f53b27eac3229906ec9d01b79fa4ec38b1da7051fd0fc2f8e7fe0bfbb589"

      def install
        bin.install "logc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/logc/releases/download/v1.0.0/logc_1.0.0_linux_arm64.tar.gz"
      sha256 "f900164cad7dd0ce37c5a804d920e791fc739f64f9a27c78f12e7c99e3ac7fbf"

      def install
        bin.install "logc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fortio/logc/releases/download/v1.0.0/logc_1.0.0_linux_amd64.tar.gz"
      sha256 "67a3c29b4fbde4f26f0d456e468668d7f1109bfeb4d27abfb434c7f7f21fb23d"

      def install
        bin.install "logc"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/logc -version")
  end
end
