# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logc < Formula
  desc "Fortio log JSON to (colorized) text converter"
  homepage "https://fortio.org/"
  version "1.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fortio/logc/releases/download/v1.3.1/logc_1.3.1_darwin_arm64.tar.gz"
      sha256 "c3e42bd0317c462784061c8f44e12ec6958fe36d91b2df37d7cfafb1197f491e"

      def install
        bin.install "logc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fortio/logc/releases/download/v1.3.1/logc_1.3.1_darwin_amd64.tar.gz"
      sha256 "65b13092eab51d2a0bb59b6a661a023974a06f205533fc65e41e318d0c86f219"

      def install
        bin.install "logc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/logc/releases/download/v1.3.1/logc_1.3.1_linux_amd64.tar.gz"
      sha256 "21b0f419494af31da2ab47028c3ceeedcdb486301ff2e4f69a05c45ae2c8b11f"

      def install
        bin.install "logc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/logc/releases/download/v1.3.1/logc_1.3.1_linux_arm64.tar.gz"
      sha256 "27033239f9df2c4d5bf8f988d9ddcd3b1a7a1b44b8e8708c0433d922ab939274"

      def install
        bin.install "logc"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/logc -version")
  end
end
