# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memstore < Formula
  desc "Fortio memstore"
  homepage "https://fortio.org/"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/memstore/releases/download/v0.1.3/memstore_0.1.3_darwin_amd64.zip"
      sha256 "7878fc1433e303d7db7041c9da96af89a166654fe1f2be6152b4a30878a0891c"

      define_method(:install) do
        bin.install "memstore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/memstore/releases/download/v0.1.3/memstore_0.1.3_darwin_arm64.zip"
      sha256 "af2d23d200cf7c48a0cd350b207e3c4cae233cbe16019acc1a829538de3df19a"

      define_method(:install) do
        bin.install "memstore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/memstore/releases/download/v0.1.3/memstore_0.1.3_linux_amd64.tar.gz"
      sha256 "e6c13345d374442902feb41967bf0ca87769ce98d51579d81a2ca7724a52170c"
      define_method(:install) do
        bin.install "memstore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/memstore/releases/download/v0.1.3/memstore_0.1.3_linux_arm64.tar.gz"
      sha256 "1539feb367b1470221c461863b39b7cd01c1d3276bdec8f64912d04ca7518416"
      define_method(:install) do
        bin.install "memstore"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/memstore -version")
  end
end
