# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memstore < Formula
  desc "Fortio memstore"
  homepage "https://fortio.org/"
  version "0.1.0-pre3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/memstore/releases/download/v0.1.0-pre3/memstore_0.1.0-pre3_darwin_amd64.tar.gz"
      sha256 "fcbde487d870bd30d97b10b39845f8a6c077e3106fe85403e639697651462d1e"

      def install
        bin.install "memstore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/memstore/releases/download/v0.1.0-pre3/memstore_0.1.0-pre3_darwin_arm64.tar.gz"
      sha256 "11078fc1d463d2545fa3adb9d3e1835849f1e1df5d52ac27ab988ec973b14c33"

      def install
        bin.install "memstore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/memstore/releases/download/v0.1.0-pre3/memstore_0.1.0-pre3_linux_arm64.tar.gz"
      sha256 "f0c526c04ef26a5ba67e75688469738eac7e02a9e3d479156c5ce7e2c311aa51"

      def install
        bin.install "memstore"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fortio/memstore/releases/download/v0.1.0-pre3/memstore_0.1.0-pre3_linux_amd64.tar.gz"
      sha256 "80e52764e9d6e068776d04d91fd393442c931f98e9d456260b6c633741b38fb7"

      def install
        bin.install "memstore"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/memstore -version")
  end
end
