# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memstore < Formula
  desc "Fortio memstore"
  homepage "https://fortio.org/"
  version "0.1.0-pre1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fortio/memstore/releases/download/v0.1.0-pre1/memstore_0.1.0-pre1_darwin_arm64.tar.gz"
      sha256 "5c17b33573c17836cdcc2b99de51bf695b05106070f8f6a73425e8cc5ecc8e4e"

      def install
        bin.install "memstore"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fortio/memstore/releases/download/v0.1.0-pre1/memstore_0.1.0-pre1_darwin_amd64.tar.gz"
      sha256 "b566c9cebccf495e5fb1c9ec3fea6521813e35ab85b16881aef47a66a6674be1"

      def install
        bin.install "memstore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/memstore/releases/download/v0.1.0-pre1/memstore_0.1.0-pre1_linux_amd64.tar.gz"
      sha256 "868e24d5334a21fa413061845c1076b0f1c4ca0c25629d79461b10d27589367a"

      def install
        bin.install "memstore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/memstore/releases/download/v0.1.0-pre1/memstore_0.1.0-pre1_linux_arm64.tar.gz"
      sha256 "64038abcaf1772f3d9c6958f924ba09277b4a13831256d9af261fec86c8f2c2a"

      def install
        bin.install "memstore"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/memstore -version")
  end
end
