# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multicurl < Formula
  desc "Fortio multi curl"
  homepage "https://fortio.org/"
  version "1.16.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/multicurl/releases/download/v1.16.6/multicurl_1.16.6_darwin_amd64.zip"
      sha256 "32b196afbc15f4136b0bc1531ce9841695e90e3baa8e053896952dde1fc45fca"

      def install
        bin.install "multicurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/multicurl/releases/download/v1.16.6/multicurl_1.16.6_darwin_arm64.zip"
      sha256 "376e1c1237b3eb0b9f7cf3823af488909b341817dacbd56ca068db65a7aeeaa5"

      def install
        bin.install "multicurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/multicurl/releases/download/v1.16.6/multicurl_1.16.6_linux_amd64.tar.gz"
        sha256 "b3251ad179c641bdfea24bbe9fec53585fa751f34afb30ae83c3cfd02ebec8ed"

        def install
          bin.install "multicurl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/multicurl/releases/download/v1.16.6/multicurl_1.16.6_linux_arm64.tar.gz"
        sha256 "3bcc75203a733a64accdb528bcf5c75112959eba3d46bb8a124a9df6c819214d"

        def install
          bin.install "multicurl"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/multicurl -version")
  end
end
