# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multicurl < Formula
  desc "Fortio multi curl"
  homepage "https://fortio.org/"
  version "1.16.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/multicurl/releases/download/v1.16.0/multicurl_1.16.0_darwin_amd64.zip"
      sha256 "3114ffc762afbc1fc6decb0eda8dd5e7a3a7e76c4b057ce69b7663325654cdb9"

      def install
        bin.install "multicurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/multicurl/releases/download/v1.16.0/multicurl_1.16.0_darwin_arm64.zip"
      sha256 "6aae93fd246a066d8223462f1cb4c5f8905cda788fc2ea0408dd61c4572f5188"

      def install
        bin.install "multicurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/multicurl/releases/download/v1.16.0/multicurl_1.16.0_linux_amd64.tar.gz"
        sha256 "5e2d6a08715afbb09eb150bc3a6e386485d4c6b75fe647803032067921156f4f"

        def install
          bin.install "multicurl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/multicurl/releases/download/v1.16.0/multicurl_1.16.0_linux_arm64.tar.gz"
        sha256 "09646f940415ce4736058262bec8aad61e30b5cc788ae59e31f9c05326e0ea4a"

        def install
          bin.install "multicurl"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/multicurl -version")
  end
end
