# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nocolor < Formula
  desc "Fortio terminal nocolor (and no other ansi code either) filter"
  homepage "https://fortio.org/"
  version "0.28.0-pre4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/terminal/releases/download/v0.28.0-pre4/nocolor_0.28.0-pre4_darwin_amd64.zip"
      sha256 "ed87590acafe797cafee7f26df4f797115e26e175a0f8cb694e4647e0c62d868"

      def install
        bin.install "nocolor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/terminal/releases/download/v0.28.0-pre4/nocolor_0.28.0-pre4_darwin_arm64.zip"
      sha256 "87d8144cf24f43ea6c4333eac94179b2081a3575294992b48f0a25eb75d9db36"

      def install
        bin.install "nocolor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/terminal/releases/download/v0.28.0-pre4/nocolor_0.28.0-pre4_linux_amd64.tar.gz"
        sha256 "f848a201231fc0269980a72373abe6d3d364e27235dd9773513b582d17647fda"

        def install
          bin.install "nocolor"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/terminal/releases/download/v0.28.0-pre4/nocolor_0.28.0-pre4_linux_arm64.tar.gz"
        sha256 "b38753588a0bf16a553c39377705f16f55dc36754310e792dd867ad4d2709088"

        def install
          bin.install "nocolor"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nocolor -version")
  end
end
