# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nocolor < Formula
  desc "Fortio terminal nocolor (and no other ansi code either) filter"
  homepage "https://fortio.org/"
  version "0.35.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/terminal/releases/download/v0.35.4/nocolor_0.35.4_darwin_amd64.zip"
      sha256 "a29232f96fb65d0c6501fd545e3bee060dccabae30785f0f9d4bd84946f260aa"

      def install
        bin.install "nocolor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/terminal/releases/download/v0.35.4/nocolor_0.35.4_darwin_arm64.zip"
      sha256 "a3c72f8660ff9877cd7d168434451b66062ad76cb4655cfb0e988471461a808a"

      def install
        bin.install "nocolor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/terminal/releases/download/v0.35.4/nocolor_0.35.4_linux_amd64.tar.gz"
        sha256 "7ac2c487bc1d821948ba2969c8c9ea1936a783189b18186fd8b811b1d2a9fc37"

        def install
          bin.install "nocolor"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/terminal/releases/download/v0.35.4/nocolor_0.35.4_linux_arm64.tar.gz"
        sha256 "4c7c3b4804381452fc7d261db9b57ed8a756027d47ad50b6b024b04ca0732396"

        def install
          bin.install "nocolor"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nocolor -version")
  end
end
