# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtelSampleApp < Formula
  desc "Go open telemetry sample app"
  homepage "https://fortio.org/"
  version "0.5.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/otel-sample-app/releases/download/v0.5.1/otel-sample-app_0.5.1_darwin_amd64.zip"
      sha256 "e87a9fff649401c4a6f47e0eb85e80088fd96adf525bd00008366bc6930eaba4"

      define_method(:install) do
        bin.install "otel-sample-app"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/otel-sample-app/releases/download/v0.5.1/otel-sample-app_0.5.1_darwin_arm64.zip"
      sha256 "5dddd41ed30d1a14dc152dadbcd4c1cbd8b0ddf79a31b4d27954693b03e40f1c"

      define_method(:install) do
        bin.install "otel-sample-app"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/otel-sample-app/releases/download/v0.5.1/otel-sample-app_0.5.1_linux_amd64.tar.gz"
      sha256 "c38646c4feeb1bba266ae89eab3633678a593f39c162e0dacc240ff1cdd7edff"
      define_method(:install) do
        bin.install "otel-sample-app"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/otel-sample-app/releases/download/v0.5.1/otel-sample-app_0.5.1_linux_arm64.tar.gz"
      sha256 "5ae0b734da98247f1d31533ed2d0f6237278df3b02bf01913a0423d2b5392eb9"
      define_method(:install) do
        bin.install "otel-sample-app"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/otel-sample-app -version")
  end
end
