# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtelSampleApp < Formula
  desc "Go open telemetry sample app"
  homepage "https://fortio.org/"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/otel-sample-app/releases/download/v0.5.0/otel-sample-app_0.5.0_darwin_amd64.zip"
      sha256 "177a47a7d1bbb2e9ad3bf4e651ec13bb9478d02c28485b0fe61b03249ed1975a"

      def install
        bin.install "otel-sample-app"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/otel-sample-app/releases/download/v0.5.0/otel-sample-app_0.5.0_darwin_arm64.zip"
      sha256 "aea3aa41fb5428865b9b78784246bee4b5382a1046dacedecd1b4b386d792326"

      def install
        bin.install "otel-sample-app"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/otel-sample-app/releases/download/v0.5.0/otel-sample-app_0.5.0_linux_amd64.tar.gz"
        sha256 "daefee1e73a8876c97f677e9aae553e4472d9a46714b9d4404369f006a1e9a72"

        def install
          bin.install "otel-sample-app"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/otel-sample-app/releases/download/v0.5.0/otel-sample-app_0.5.0_linux_arm64.tar.gz"
        sha256 "a517239e5324bda61265fd7972fdae2b006f1ab0d8a6ca82f3b6cbc7a80a3d62"

        def install
          bin.install "otel-sample-app"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/otel-sample-app -version")
  end
end
