# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtelSampleApp < Formula
  desc "Go open telemetry sample app"
  homepage "https://fortio.org/"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/fortio/otel-sample-app/releases/download/v0.4.0/otel-sample-app_0.4.0_darwin_amd64.tar.gz"
      sha256 "8ce04359237161fd42b6be25e390113917ee89d0b86a66f8c44d4d7f9d075653"

      def install
        bin.install "otel-sample-app"
      end
    end
    on_arm do
      url "https://github.com/fortio/otel-sample-app/releases/download/v0.4.0/otel-sample-app_0.4.0_darwin_arm64.tar.gz"
      sha256 "fa1d77940c8608d9c6dceecd582c606ff4120ad9ab30649ccab22686ffd7f6bc"

      def install
        bin.install "otel-sample-app"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/otel-sample-app/releases/download/v0.4.0/otel-sample-app_0.4.0_linux_amd64.tar.gz"
        sha256 "b925ae9022fc226068f5cb15302c5eb158f2fc9e9a4694f26001a90d7b365e88"

        def install
          bin.install "otel-sample-app"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/otel-sample-app/releases/download/v0.4.0/otel-sample-app_0.4.0_linux_arm64.tar.gz"
        sha256 "8c307f187f1449da577430515441838926ca5e1e314a5043e11f3b1ffb8d87e2"

        def install
          bin.install "otel-sample-app"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/otel-sample-app -version")
  end
end
