# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PanicLinter < Formula
  desc "Go panic linter"
  homepage "https://fortio.org/"
  version "0.2.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ldemailly/panic-linter/releases/download/v0.2.5/panic-linter_0.2.5_darwin_amd64.zip"
      sha256 "b23f531909cf4edceb209ab8725a49ea5700954facb7477d077bcfb259f6c7db"

      def install
        bin.install "panic-linter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ldemailly/panic-linter/releases/download/v0.2.5/panic-linter_0.2.5_darwin_arm64.zip"
      sha256 "faa035611449f1c5bd76e10da6e50fc87f1d03e34996ccb009409e0f227b9d89"

      def install
        bin.install "panic-linter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ldemailly/panic-linter/releases/download/v0.2.5/panic-linter_0.2.5_linux_amd64.tar.gz"
      sha256 "66fc2249561bac58edb548b8ed403d395e390900a24ce4a1e77d212d9bf67b98"
      def install
        bin.install "panic-linter"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ldemailly/panic-linter/releases/download/v0.2.5/panic-linter_0.2.5_linux_arm64.tar.gz"
      sha256 "723c85c5cefbaeee4dc624eb54c3a23a25799682a98f124facefa78a2c2f944f"
      def install
        bin.install "panic-linter"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/panic-linter -version")
  end
end
