# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PanicLinter < Formula
  desc "Go panic linter"
  homepage "https://fortio.org/"
  version "0.2.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ldemailly/panic-linter/releases/download/v0.2.6/panic-linter_0.2.6_darwin_amd64.zip"
      sha256 "b44046b74b7109b65099f18dbe7f07f8de74998ed2e69a6cba0e77462202b1d6"

      def install
        bin.install "panic-linter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ldemailly/panic-linter/releases/download/v0.2.6/panic-linter_0.2.6_darwin_arm64.zip"
      sha256 "817b5e83cd88c9aa04095a0c9e59590b0aecb36e52b3afd7a8649e30a7d24874"

      def install
        bin.install "panic-linter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ldemailly/panic-linter/releases/download/v0.2.6/panic-linter_0.2.6_linux_amd64.tar.gz"
      sha256 "52ba8fba0f66b199e7d2ff6b5402c1674ff6e12c18b2d34b8219cd37e0aeba08"
      def install
        bin.install "panic-linter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ldemailly/panic-linter/releases/download/v0.2.6/panic-linter_0.2.6_linux_arm64.tar.gz"
      sha256 "25006ec3d047cc5b1162b48ea1944e48772b119df4a03ca23a98d1539429c068"
      def install
        bin.install "panic-linter"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/panic-linter -version")
  end
end
