# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PanicLinter < Formula
  desc "Go panic linter"
  homepage "https://fortio.org/"
  version "0.2.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ldemailly/panic-linter/releases/download/v0.2.7/panic-linter_0.2.7_darwin_amd64.zip"
      sha256 "2a7eaaf1776cf108608c5cb15cc48f975474be1e47fc06d5b4f42bec07506540"

      define_method(:install) do
        bin.install "panic-linter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ldemailly/panic-linter/releases/download/v0.2.7/panic-linter_0.2.7_darwin_arm64.zip"
      sha256 "5ca0250f38834afff9bcc3643823a9d13732a433c54833018fa99c6e74a4926d"

      define_method(:install) do
        bin.install "panic-linter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ldemailly/panic-linter/releases/download/v0.2.7/panic-linter_0.2.7_linux_amd64.tar.gz"
      sha256 "362b4d13217db788c003b642e86027c4c956eff8417886f42e569b973d56cd43"
      define_method(:install) do
        bin.install "panic-linter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ldemailly/panic-linter/releases/download/v0.2.7/panic-linter_0.2.7_linux_arm64.tar.gz"
      sha256 "28cda4830a04952568eeb5bbd697130927b262a32a4e89c6f68d11eb4968eecd"
      define_method(:install) do
        bin.install "panic-linter"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/panic-linter -version")
  end
end
