# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proxy < Formula
  desc "TLS ingress reverse proxy and multiplexer with autocert and simple routing rules"
  homepage "https://fortio.org/"
  version "1.25.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/proxy/releases/download/v1.25.2/proxy_1.25.2_darwin_amd64.zip"
      sha256 "3f1c3f22c7218816cbc572dba70a57f4078a31646dff190e125a3b06ede54b07"

      def install
        bin.install "proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/proxy/releases/download/v1.25.2/proxy_1.25.2_darwin_arm64.zip"
      sha256 "4ddeb8275884d39fa97e6deab44ed7b9adff4851e2b1eb2786bded2a9d9cb498"

      def install
        bin.install "proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/proxy/releases/download/v1.25.2/proxy_1.25.2_linux_amd64.tar.gz"
        sha256 "1bfa413e0a968e757867d9e5cbcf0b02f9f0acde2915110d235015908be4d8f4"

        def install
          bin.install "proxy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/proxy/releases/download/v1.25.2/proxy_1.25.2_linux_arm64.tar.gz"
        sha256 "48914dada82f501c18407f184bacd2c6d9612fdf0ea02f5ef6beec0d089332bf"

        def install
          bin.install "proxy"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/proxy -version")
  end
end
