# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quartiles < Formula
  desc "Go open telemetry sample app"
  homepage "https://fortio.org/"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/ldemailly/quartiles/releases/download/v0.2.0/quartiles_0.2.0_darwin_amd64.tar.gz"
      sha256 "c087cdf6d7054dfa756672ed03595dc8283e1f180224a51a110c37f11b8628a3"

      def install
        bin.install "quartiles"
      end
    end
    on_arm do
      url "https://github.com/ldemailly/quartiles/releases/download/v0.2.0/quartiles_0.2.0_darwin_arm64.tar.gz"
      sha256 "d246a1c485a5f5bd5667c0aef565f673d71addedb542d52062e293fbee9e8471"

      def install
        bin.install "quartiles"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldemailly/quartiles/releases/download/v0.2.0/quartiles_0.2.0_linux_amd64.tar.gz"
        sha256 "0998ab10a5ae736163115a7dc9e40ff897184a275f2a12d5e7345f0af0c97bc8"

        def install
          bin.install "quartiles"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldemailly/quartiles/releases/download/v0.2.0/quartiles_0.2.0_linux_arm64.tar.gz"
        sha256 "d5d596347bcc212ab97e4636bf2429d1fab7e7978c45322ca7407f6d07f36487"

        def install
          bin.install "quartiles"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/quartiles -version")
  end
end
