# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quartiles < Formula
  desc "Go open telemetry sample app"
  homepage "https://fortio.org/"
  version "0.1.5"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/ldemailly/quartiles/releases/download/v0.1.5/quartiles_0.1.5_darwin_amd64.tar.gz"
      sha256 "aedbe122c75ca3baed298851e2393f1b602acc963012bc3c2fbe7be3cd5b3efd"

      def install
        bin.install "quartiles"
      end
    end
    on_arm do
      url "https://github.com/ldemailly/quartiles/releases/download/v0.1.5/quartiles_0.1.5_darwin_arm64.tar.gz"
      sha256 "454528cb64b8b4356f7d200ab28e901b86153f87cfb009a081edcb5c79ed2b9d"

      def install
        bin.install "quartiles"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldemailly/quartiles/releases/download/v0.1.5/quartiles_0.1.5_linux_amd64.tar.gz"
        sha256 "c4b9365185fc0722a1e6cd71a5b7ad698924c170633f13c03b47b0767e76d11b"

        def install
          bin.install "quartiles"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldemailly/quartiles/releases/download/v0.1.5/quartiles_0.1.5_linux_arm64.tar.gz"
        sha256 "4b1f9ec563c7ac3b51fef6d5d052279dca6d6a76e756392c605200c9732f282e"

        def install
          bin.install "quartiles"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/quartiles -version")
  end
end
