# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackProxy < Formula
  desc "Proxy for applications aiming to dispatch messages to Slack nicely"
  homepage "https://fortio.org/"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/slack-proxy/releases/download/v0.9.0/slack-proxy_0.9.0_darwin_amd64.zip"
      sha256 "ba337224dbe7d19e7c66daa4cc2ed6680769a2b666125b16f735e84c2a4f9e31"

      def install
        bin.install "slack-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/slack-proxy/releases/download/v0.9.0/slack-proxy_0.9.0_darwin_arm64.zip"
      sha256 "5486c9218c56b29e312a2b50955b7f6229965cb9a70d665dbe17393c505768bd"

      def install
        bin.install "slack-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/slack-proxy/releases/download/v0.9.0/slack-proxy_0.9.0_linux_amd64.tar.gz"
      sha256 "558bb63dc668f39983a7a208c1c8bef4d94e1871f59dcef81906a2bbae0d0fd3"
      def install
        bin.install "slack-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/slack-proxy/releases/download/v0.9.0/slack-proxy_0.9.0_linux_arm64.tar.gz"
      sha256 "eb4180995657b4e18af264775a60b789f22cf32748b96137d2eb6ab7b740a475"
      def install
        bin.install "slack-proxy"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/slack-proxy -version")
  end
end
