# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshd < Formula
  desc "Ansipixels sshd demoes menu server"
  homepage "https://fortio.org/"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/sshd/releases/download/v0.4.0/sshd_0.4.0_darwin_amd64.zip"
      sha256 "747c3f61d6e8ec6608cdb085725607cfb5b510b2d2188b0927c24c2592d39d19"

      def install
        bin.install "sshd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/sshd/releases/download/v0.4.0/sshd_0.4.0_darwin_arm64.zip"
      sha256 "a2fca9325b703062f9943ce727b99d115e5f097c4c02251a3bffd2171e551360"

      def install
        bin.install "sshd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/sshd/releases/download/v0.4.0/sshd_0.4.0_linux_amd64.tar.gz"
      sha256 "8830812afb345e53f3872262ddad64e32ca4b22089612770d4db4edd6bf9c5ac"
      def install
        bin.install "sshd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/sshd/releases/download/v0.4.0/sshd_0.4.0_linux_arm64.tar.gz"
      sha256 "039f342578251fad541bc1eb16add3abd752b519017d715e68a41d025918c4f3"
      def install
        bin.install "sshd"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sshd -version")
  end
end
