# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshdtui < Formula
  desc "Ansipixels sshd tui demoes menu server"
  homepage "https://fortio.org/"
  version "0.7.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/sshdtui/releases/download/v0.7.2/sshdtui_0.7.2_darwin_amd64.zip"
      sha256 "c3f510806c9f16d362d4a498ccef2aec01103e230da25f857fa8b0f0fcce8798"

      def install
        bin.install "sshdtui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/sshdtui/releases/download/v0.7.2/sshdtui_0.7.2_darwin_arm64.zip"
      sha256 "fc1f1e0fa9e4f0f0182230bda1641721b946a4c99fdc584558d022c2bfae9b28"

      def install
        bin.install "sshdtui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/sshdtui/releases/download/v0.7.2/sshdtui_0.7.2_linux_amd64.tar.gz"
      sha256 "ef190c6b7d4db645156a6eea1de005c59c15465b9ea0ba7b9edec0379b78cd05"
      def install
        bin.install "sshdtui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/sshdtui/releases/download/v0.7.2/sshdtui_0.7.2_linux_arm64.tar.gz"
      sha256 "9fa26b8a694e3eb35c3d2bd440a5ef5fe4db52071d95df48e91f9ecff579b4e7"
      def install
        bin.install "sshdtui"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sshdtui -version")
  end
end
