# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshdtui < Formula
  desc "Ansipixels sshd tui demoes menu server"
  homepage "https://fortio.org/"
  version "0.7.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/sshdtui/releases/download/v0.7.4/sshdtui_0.7.4_darwin_amd64.zip"
      sha256 "6d8948ad4487e4cc2cf50ee350c5177821beda70128de27a50864b5266810d10"

      define_method(:install) do
        bin.install "sshdtui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/sshdtui/releases/download/v0.7.4/sshdtui_0.7.4_darwin_arm64.zip"
      sha256 "4676a24a067698c496f6ca9103bdcc634ce55d9c1f0913bb17afe6d390606547"

      define_method(:install) do
        bin.install "sshdtui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/sshdtui/releases/download/v0.7.4/sshdtui_0.7.4_linux_amd64.tar.gz"
      sha256 "8f4937d7c323dd6bf7515d396db5afe65001063e995aef6ae223d0370d5a184a"
      define_method(:install) do
        bin.install "sshdtui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/sshdtui/releases/download/v0.7.4/sshdtui_0.7.4_linux_arm64.tar.gz"
      sha256 "840fc77296884695c226629103d712d5caa7c3c985297e705bcf59a402f71385"
      define_method(:install) do
        bin.install "sshdtui"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sshdtui -version")
  end
end
