# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tbonsai < Formula
  desc "Fortio tbonsai Ansipixels port of cbonsai"
  homepage "https://fortio.org/"
  version "1.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tbonsai/releases/download/v1.1.2/tbonsai_1.1.2_darwin_amd64.zip"
      sha256 "15a765bf978562be4b1780a9e34b674f50b429827f6af89a79d4f61144e1ae54"

      def install
        bin.install "tbonsai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tbonsai/releases/download/v1.1.2/tbonsai_1.1.2_darwin_arm64.zip"
      sha256 "d95d744d25b5355431f7de6cb4c029c1eb3efb584b78bea23226743c7332b981"

      def install
        bin.install "tbonsai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tbonsai/releases/download/v1.1.2/tbonsai_1.1.2_linux_amd64.tar.gz"
      sha256 "a3aa1e2cb568015448ae7cb192cdf95eceb05a5836e19cfa8a76630016b18627"
      def install
        bin.install "tbonsai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tbonsai/releases/download/v1.1.2/tbonsai_1.1.2_linux_arm64.tar.gz"
      sha256 "31f21465ae7d162f388e68c8d1c6af683445e1f940751df0a4562a8e4e84d20b"
      def install
        bin.install "tbonsai"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tbonsai -version")
  end
end
