# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tbonsai < Formula
  desc "Fortio tbonsai Ansipixels port of cbonsai"
  homepage "https://fortio.org/"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tbonsai/releases/download/v1.1.0/tbonsai_1.1.0_darwin_amd64.zip"
      sha256 "c56e4f9a6d8ed12be8679b67cbd82d42b7719ad372b30a8f27e3ede7760c5773"

      def install
        bin.install "tbonsai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tbonsai/releases/download/v1.1.0/tbonsai_1.1.0_darwin_arm64.zip"
      sha256 "3679ad53d1f7a81b6fb559b25ac5366c8c5f77bf677b77c27b0fbc64eed3330f"

      def install
        bin.install "tbonsai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tbonsai/releases/download/v1.1.0/tbonsai_1.1.0_linux_amd64.tar.gz"
      sha256 "36701f5738b271cfab01fe4fe0d013bfa6b157713163637fb43e5e0c0457c3f7"
      def install
        bin.install "tbonsai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tbonsai/releases/download/v1.1.0/tbonsai_1.1.0_linux_arm64.tar.gz"
      sha256 "3abdbdcb9d62296569ae68a8986168065bfdb93b8d04d6338ed3ca9ac2f04c9d"
      def install
        bin.install "tbonsai"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tbonsai -version")
  end
end
