# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tcalc < Formula
  desc "tcalc is a bitwise calculator that is run from the terminal. It supports basic variable assignments, and most arithmetic and bitwise operations."
  homepage "https://fortio.org/"
  version "0.7.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tcalc/releases/download/v0.7.6/tcalc_0.7.6_darwin_amd64.zip"
      sha256 "e597e27e78bf59007b8602d5ba3f17a2bf1ae79751cea3fad619f2ec4ac832a5"

      def install
        bin.install "tcalc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tcalc/releases/download/v0.7.6/tcalc_0.7.6_darwin_arm64.zip"
      sha256 "5649c3882b467933e8a3b3b3acfa91bf536a91829ef4fe62c53f8e6b48be29b0"

      def install
        bin.install "tcalc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tcalc/releases/download/v0.7.6/tcalc_0.7.6_linux_amd64.tar.gz"
      sha256 "b3f97fb6e47c728a9689c0cb7a4cc6fcda08f95755a04f0796543c88647e24ed"
      def install
        bin.install "tcalc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tcalc/releases/download/v0.7.6/tcalc_0.7.6_linux_arm64.tar.gz"
      sha256 "314df39ca1719f745fb0cdff367cc5c106e5650f98ee801a07141f01e0723189"
      def install
        bin.install "tcalc"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tcalc -version")
  end
end
