# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tcalc < Formula
  desc "tcalc is a bitwise calculator that is run from the terminal. It supports basic variable assignments, and most arithmetic and bitwise operations."
  homepage "https://fortio.org/"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tcalc/releases/download/v0.2.1/tcalc_0.2.1_darwin_amd64.zip"
      sha256 "7b91d9253d8c66c66ca659d9f9d0a96bcac56f173f24b28de32ac4afcd7d3a69"

      def install
        bin.install "tcalc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tcalc/releases/download/v0.2.1/tcalc_0.2.1_darwin_arm64.zip"
      sha256 "353080704d886b2c453ac3b0ef14332f0ea84a00126eb1a927a01d5f7d866357"

      def install
        bin.install "tcalc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tcalc/releases/download/v0.2.1/tcalc_0.2.1_linux_amd64.tar.gz"
      sha256 "fc6eba89450360499929ee10b4a8f0e0eab5829cfa0721536429da43c0d64460"
      def install
        bin.install "tcalc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tcalc/releases/download/v0.2.1/tcalc_0.2.1_linux_arm64.tar.gz"
      sha256 "a65d8a3d2674512a3298f8c35cfb57894a8b39aa6d5515b2810aa3aa0ae98825"
      def install
        bin.install "tcalc"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tcalc -version")
  end
end
