# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tclock < Formula
  desc "Fortio terminal clock"
  homepage "https://fortio.org/"
  version "1.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tclock/releases/download/v1.4.0/tclock_1.4.0_darwin_amd64.zip"
      sha256 "64a14f01bc6674f044c0f9930b656cb5226f747819544cc7a97c25f26511eade"

      def install
        bin.install "tclock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tclock/releases/download/v1.4.0/tclock_1.4.0_darwin_arm64.zip"
      sha256 "abdcbb81d400efa159c369108adc1fefd90127879082bdf7b9076ea7c6f98265"

      def install
        bin.install "tclock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tclock/releases/download/v1.4.0/tclock_1.4.0_linux_amd64.tar.gz"
      sha256 "8fda03f9cfeef8e1de79d80a6df8690bc764a104579472ad3bdf0989627e8567"
      def install
        bin.install "tclock"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tclock/releases/download/v1.4.0/tclock_1.4.0_linux_arm64.tar.gz"
      sha256 "5f5b276beee0f58fb7b0b7236d240b4babc74ec3050964bdbbb28bec46482ae6"
      def install
        bin.install "tclock"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tclock -version")
  end
end
