# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tcolor < Formula
  desc "Fortio terminal color picker"
  homepage "https://fortio.org/"
  version "1.5.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tcolor/releases/download/v1.5.5/tcolor_1.5.5_darwin_amd64.zip"
      sha256 "950599a74505c40c12a4c2bf4c26c8ae32ba81079e9e323681f26ae5c9cbe3f9"

      def install
        bin.install "tcolor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tcolor/releases/download/v1.5.5/tcolor_1.5.5_darwin_arm64.zip"
      sha256 "80e6b6a6fcf9ea6bf71f2d04f3751069f7c7a2e910b25128b76bfec2a2e983df"

      def install
        bin.install "tcolor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tcolor/releases/download/v1.5.5/tcolor_1.5.5_linux_amd64.tar.gz"
      sha256 "bd45be002f7c190407cdb546d90ab1e107017304dbc4841a226783ee696ee730"
      def install
        bin.install "tcolor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tcolor/releases/download/v1.5.5/tcolor_1.5.5_linux_arm64.tar.gz"
      sha256 "90535282da7c5c12c10e239138035c2155943ef0885fd5790f824e3fb9cdf424"
      def install
        bin.install "tcolor"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tcolor -version")
  end
end
