# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terminal < Formula
  desc "Fortio terminal fps checker"
  homepage "https://fortio.org/"
  version "0.10.0-pre11"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/fortio/terminal/releases/download/v0.10.0-pre11/terminal_0.10.0-pre11_darwin_amd64.zip"
      sha256 "fcc688cda9e807a8130b75bd579d9761c4585de1f66eb2ad7abddde89c8dd8cb"

      def install
        bin.install "fps"
      end
    end
    on_arm do
      url "https://github.com/fortio/terminal/releases/download/v0.10.0-pre11/terminal_0.10.0-pre11_darwin_arm64.zip"
      sha256 "4453432e02093f324267eca2edcccd28f266e02f66d1f80cd7aef6638eac7f5c"

      def install
        bin.install "fps"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/terminal/releases/download/v0.10.0-pre11/terminal_0.10.0-pre11_linux_amd64.tar.gz"
        sha256 "3e23b27cf5dc2694b4e43eb8c4aae817cb28263cea2a8363d999e1eccbccc492"

        def install
          bin.install "fps"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/terminal/releases/download/v0.10.0-pre11/terminal_0.10.0-pre11_linux_arm64.tar.gz"
        sha256 "cf64cb675e4e0970bc547ca52a8ce5faca35ddecf476fef3b361cc21b2578314"

        def install
          bin.install "fps"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fps -version")
  end
end
