# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terminal < Formula
  desc "Fortio terminal fps checker"
  homepage "https://fortio.org/"
  version "0.10.0-pre13"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/fortio/terminal/releases/download/v0.10.0-pre13/fps_0.10.0-pre13_darwin_amd64.zip"
      sha256 "7a2ddd8449e9ff178f6c2e83f4deab6ad39817f278c96ca136117fb4070aecf6"

      def install
        bin.install "fps"
      end
    end
    on_arm do
      url "https://github.com/fortio/terminal/releases/download/v0.10.0-pre13/fps_0.10.0-pre13_darwin_arm64.zip"
      sha256 "5feab2ede564d45732142c00e94fab34be2520c27eefcb125c7f0be028318bb3"

      def install
        bin.install "fps"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/terminal/releases/download/v0.10.0-pre13/fps_0.10.0-pre13_linux_amd64.tar.gz"
        sha256 "c662c07e30b1c9cd6cec22bfcb62fb9a58f7dc8a396b26e17c611c2b3084a29e"

        def install
          bin.install "fps"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/terminal/releases/download/v0.10.0-pre13/fps_0.10.0-pre13_linux_arm64.tar.gz"
        sha256 "a9f52a6e8ae9cdd766b87d921773ea3ce2af10c5a68f78ad127ecf6359383c23"

        def install
          bin.install "fps"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fps -version")
  end
end
