# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tev < Formula
  desc "Fortio terminal terminal event debug"
  homepage "https://fortio.org/"
  version "0.10.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tev/releases/download/v0.10.2/tev_0.10.2_darwin_amd64.zip"
      sha256 "98d7ec8ef839f7ec363e64c89b79aafe5fea063fed778943fb9dcfd33fa02b91"

      def install
        bin.install "tev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tev/releases/download/v0.10.2/tev_0.10.2_darwin_arm64.zip"
      sha256 "2260dfa5342e487f18dc55605c9261882f2d227655da37a38d6737df22f02b27"

      def install
        bin.install "tev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tev/releases/download/v0.10.2/tev_0.10.2_linux_amd64.tar.gz"
      sha256 "5ef640c1647cc85ddb4e5539a9988c95b02abe0af82122f02480e041371b5f7e"
      def install
        bin.install "tev"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tev/releases/download/v0.10.2/tev_0.10.2_linux_arm64.tar.gz"
      sha256 "495ef25b55918e2dd2212d165ae02d7893d8095a82d15a372dd4ee53ae24d0fb"
      def install
        bin.install "tev"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tev -version")
  end
end
