# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfonts < Formula
  desc "Fortio terminal large text output using your TTF fonts"
  homepage "https://fortio.org/"
  version "1.3.0-pre3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tfonts/releases/download/v1.3.0-pre3/tfonts_1.3.0-pre3_darwin_amd64.zip"
      sha256 "e1646c62984f06093651fc3d14b94369b648266d63c0c3778d4dfd5f09ef92f2"

      def install
        bin.install "tfonts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tfonts/releases/download/v1.3.0-pre3/tfonts_1.3.0-pre3_darwin_arm64.zip"
      sha256 "6dc857cc9b84621dd472d0f5a1e88666baa2523bcecafcc40987ed0c11984e41"

      def install
        bin.install "tfonts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tfonts/releases/download/v1.3.0-pre3/tfonts_1.3.0-pre3_linux_amd64.tar.gz"
      sha256 "a767a60a8116bf8ef2126ca1562610afd9475e5b0c4e0c21d7f81e2dce0a5984"
      def install
        bin.install "tfonts"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tfonts/releases/download/v1.3.0-pre3/tfonts_1.3.0-pre3_linux_arm64.tar.gz"
      sha256 "879bf90442785e1d581ccdd933c667f62e44fcbb9dd07d8589a4c125521541e2"
      def install
        bin.install "tfonts"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfonts -version")
  end
end
