# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfonts < Formula
  desc "Fortio terminal large text output using your TTF fonts"
  homepage "https://fortio.org/"
  version "1.5.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tfonts/releases/download/v1.5.3/tfonts_1.5.3_darwin_amd64.zip"
      sha256 "2bd736bff8c2a4be077b0e7469d09e99c2afd6b830c09bb9bce23e198664962a"

      def install
        bin.install "tfonts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tfonts/releases/download/v1.5.3/tfonts_1.5.3_darwin_arm64.zip"
      sha256 "2b8bf376fba7733a0dc08f088687585a0678f8b2f4ffd85c631412ce5703d1f8"

      def install
        bin.install "tfonts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tfonts/releases/download/v1.5.3/tfonts_1.5.3_linux_amd64.tar.gz"
      sha256 "4d3ea0c0f14fdb8f4433aff4a74d3bfaea92c06a2176e66b0a544cb72ccf78c8"
      def install
        bin.install "tfonts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tfonts/releases/download/v1.5.3/tfonts_1.5.3_linux_arm64.tar.gz"
      sha256 "5ad281583a2f24ad3d42638382c94fa12206771ba358b0724f7fed00fc69def3"
      def install
        bin.install "tfonts"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfonts -version")
  end
end
