# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfonts < Formula
  desc "Fortio terminal large text output using your TTF fonts"
  homepage "https://fortio.org/"
  version "1.4.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tfonts/releases/download/v1.4.2/tfonts_1.4.2_darwin_amd64.zip"
      sha256 "509211b782dbaac4d1635ce24dfb0d252a06f4327de9175bddc07419bc5b03d2"

      def install
        bin.install "tfonts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tfonts/releases/download/v1.4.2/tfonts_1.4.2_darwin_arm64.zip"
      sha256 "4d685881cdc5879d1e1118ba43f66ac71ce78729416c2f7c627578f952427e29"

      def install
        bin.install "tfonts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tfonts/releases/download/v1.4.2/tfonts_1.4.2_linux_amd64.tar.gz"
      sha256 "a7fcd629ce05214b87d141f5a7b27af39d37467bba2c7243e4f820514d2ab04f"
      def install
        bin.install "tfonts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tfonts/releases/download/v1.4.2/tfonts_1.4.2_linux_arm64.tar.gz"
      sha256 "4a9c41a3ba2858c8163190a2e85907bd91e9393722923d1130f6032e00240138"
      def install
        bin.install "tfonts"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfonts -version")
  end
end
