# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmatrix < Formula
  desc "Simulate the matrix effect in your terminal"
  homepage "https://fortio.org/"
  version "0.2.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tmatrix/releases/download/v0.2.4/tmatrix_0.2.4_darwin_amd64.zip"
      sha256 "8aeb8433891270fe27a5879275dd2229435978a1fbeacd3b5eb52af64340ef4e"

      def install
        bin.install "tmatrix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tmatrix/releases/download/v0.2.4/tmatrix_0.2.4_darwin_arm64.zip"
      sha256 "cd04cf233bab29488397553e84322ebac1abb3ea145487e42d4a94c6de2c5d0d"

      def install
        bin.install "tmatrix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tmatrix/releases/download/v0.2.4/tmatrix_0.2.4_linux_amd64.tar.gz"
      sha256 "ea6ed5d5c58be748945386559fa61f0a9a3d12b8d2beaa965538f9e2842bb4df"
      def install
        bin.install "tmatrix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tmatrix/releases/download/v0.2.4/tmatrix_0.2.4_linux_arm64.tar.gz"
      sha256 "c3ef6f8f46044ba15222031f97ed3802758b05c892d436d3985a665fb302ed91"
      def install
        bin.install "tmatrix"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tmatrix -version")
  end
end
