# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tray < Formula
  desc "Fortio Ray tracing in the Terminal"
  homepage "https://fortio.org/"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tray/releases/download/v0.8.0/tray_0.8.0_darwin_amd64.zip"
      sha256 "9506f3fa39e998cfada8e0765a4028fe38fa1a53544bf14ce375f023470d1d1f"

      def install
        bin.install "tray"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tray/releases/download/v0.8.0/tray_0.8.0_darwin_arm64.zip"
      sha256 "d79392846bbcff55b452eae74cfc9059213b6d7eb6c75b14cd5a669ccc9b613b"

      def install
        bin.install "tray"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tray/releases/download/v0.8.0/tray_0.8.0_linux_amd64.tar.gz"
      sha256 "73a4518595bf36a4139e2d5bb3c75d517af932af5b5d77ff2d6b56a579ff04fa"
      def install
        bin.install "tray"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tray/releases/download/v0.8.0/tray_0.8.0_linux_arm64.tar.gz"
      sha256 "f399671ee99e3321036ea68fe907fb71b0fd5c9d076237f0cbc9ff9e54a432a2"
      def install
        bin.install "tray"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tray -version")
  end
end
