# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tray < Formula
  desc "Fortio Ray tracing in the Terminal"
  homepage "https://fortio.org/"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tray/releases/download/v1.0.0/tray_1.0.0_darwin_amd64.zip"
      sha256 "5e2a3474c5231f90249a109f85779cec70fe5de5420f8eb4ff130bd8123a9b1a"

      def install
        bin.install "tray"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tray/releases/download/v1.0.0/tray_1.0.0_darwin_arm64.zip"
      sha256 "761188208f7bd1fe3c40171eca1dc1aa246a55f6875878350495521883c72d76"

      def install
        bin.install "tray"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tray/releases/download/v1.0.0/tray_1.0.0_linux_amd64.tar.gz"
      sha256 "2117e0d8ed3e51f37f0f6da097cf0f6147bef322989b35be919318c68d8e1593"
      def install
        bin.install "tray"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tray/releases/download/v1.0.0/tray_1.0.0_linux_arm64.tar.gz"
      sha256 "6258df3471da4e5bcdd834f42039951b1466ca66b14f41056a6514bd61bd51c6"
      def install
        bin.install "tray"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tray -version")
  end
end
