# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsnake < Formula
  desc "Play the classic game of snake in the terminal"
  homepage "https://fortio.org/"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tsnake/releases/download/v0.2.2/tsnake_0.2.2_darwin_amd64.zip"
      sha256 "621eea98411cd1053c6492809f14454dd9f27317c58664bd887633e4b293f1ee"

      def install
        bin.install "tsnake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tsnake/releases/download/v0.2.2/tsnake_0.2.2_darwin_arm64.zip"
      sha256 "9ac05df514d259bf6ea3079394eb0db9c7762e07ebf330dc54b24a49912134c6"

      def install
        bin.install "tsnake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tsnake/releases/download/v0.2.2/tsnake_0.2.2_linux_amd64.tar.gz"
      sha256 "b9c058bfaa30993b16eaaf3302e3a86f0b9f7dc194a0a6d353752aabbe9bd988"
      def install
        bin.install "tsnake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tsnake/releases/download/v0.2.2/tsnake_0.2.2_linux_arm64.tar.gz"
      sha256 "f09e38ddaa97322bd3ad40c14d64f18d45ef1ce0c7f25e25fd52d847393094b0"
      def install
        bin.install "tsnake"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tsnake -version")
  end
end
