# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsnake < Formula
  desc "Play the classic game of snake in the terminal"
  homepage "https://fortio.org/"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tsnake/releases/download/v0.1.0/tsnake_0.1.0_darwin_amd64.zip"
      sha256 "27e3b4a545b02145fb1c6309ee8618596787725e88319d318f752af6e6711b13"

      def install
        bin.install "tsnake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tsnake/releases/download/v0.1.0/tsnake_0.1.0_darwin_arm64.zip"
      sha256 "5f2e68f4ed90f3cd2daa5041d071efcb12d7cacedad539390824cbb4dfe6722a"

      def install
        bin.install "tsnake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tsnake/releases/download/v0.1.0/tsnake_0.1.0_linux_amd64.tar.gz"
      sha256 "620c0e7620264fa67ed6fe228855163fe17e1b4d79f32708f84b8bb10b5bf816"
      def install
        bin.install "tsnake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tsnake/releases/download/v0.1.0/tsnake_0.1.0_linux_arm64.tar.gz"
      sha256 "db3558f74cd2b2b98d78399f64b343da03a23a7b7f56e6fecb2150cff310e848"
      def install
        bin.install "tsnake"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tsnake -version")
  end
end
