# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsnake < Formula
  desc "Play the classic game of snake in the terminal"
  homepage "https://fortio.org/"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tsnake/releases/download/v0.2.3/tsnake_0.2.3_darwin_amd64.zip"
      sha256 "0955537736d0522f3bc115d358624f6162ff085789e27da1cbdf856981911438"

      def install
        bin.install "tsnake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tsnake/releases/download/v0.2.3/tsnake_0.2.3_darwin_arm64.zip"
      sha256 "5a2d1054ac5873d8e5f7a56f99af39e2c06e2c595c7c15883c14a8991bc4985e"

      def install
        bin.install "tsnake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tsnake/releases/download/v0.2.3/tsnake_0.2.3_linux_amd64.tar.gz"
      sha256 "f6aa327989ceee83344f532b75c208def90d86333c8db1b170bef619810c94f5"
      def install
        bin.install "tsnake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tsnake/releases/download/v0.2.3/tsnake_0.2.3_linux_arm64.tar.gz"
      sha256 "58c0d5512319c92b055c2de479d1ff4d69d0707955eeb1154c1715e1de9f98cf"
      def install
        bin.install "tsnake"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tsnake -version")
  end
end
