# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsync < Formula
  desc "Fortio secure synchronization between machines"
  homepage "https://fortio.org/"
  version "0.12.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tsync/releases/download/v0.12.1/tsync_0.12.1_darwin_amd64.zip"
      sha256 "340acc835e2a8117a97a41f9e60205c284bee9700295bfe12ab3772859fecbaa"

      define_method(:install) do
        bin.install "tsync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tsync/releases/download/v0.12.1/tsync_0.12.1_darwin_arm64.zip"
      sha256 "5986e19687f15bd667592947c725ddbe892f63b1471b11acf594c9553a4014d1"

      define_method(:install) do
        bin.install "tsync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tsync/releases/download/v0.12.1/tsync_0.12.1_linux_amd64.tar.gz"
      sha256 "341591a2ed6ae20c6b44429166ff544797d444a613886bf0ad84e1447073fb34"
      define_method(:install) do
        bin.install "tsync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tsync/releases/download/v0.12.1/tsync_0.12.1_linux_arm64.tar.gz"
      sha256 "4dc7adcf9ead6ba8a2e84905e4058ea35900dd83bc6672abb3fa4947cdb7bbf3"
      define_method(:install) do
        bin.install "tsync"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tsync -version")
  end
end
