# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsync < Formula
  desc "Fortio secure synchronization between machines"
  homepage "https://fortio.org/"
  version "0.3.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/tsync/releases/download/v0.3.3/tsync_0.3.3_darwin_amd64.zip"
      sha256 "ba257d62bf78f92a56341af62b02aed6bb6c9c6ccf5aeee5f646ce639f8735ca"

      def install
        bin.install "tsync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/tsync/releases/download/v0.3.3/tsync_0.3.3_darwin_arm64.zip"
      sha256 "7d91fb95ff80664d29c2af869cce30259a752aa043abff1978ce86e11fc9a81c"

      def install
        bin.install "tsync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tsync/releases/download/v0.3.3/tsync_0.3.3_linux_amd64.tar.gz"
      sha256 "d6a708d26b13168faa45c08314d828dff53a9221446b99082c15b0caab3a2503"
      def install
        bin.install "tsync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/tsync/releases/download/v0.3.3/tsync_0.3.3_linux_arm64.tar.gz"
      sha256 "c24901985bd28e24937bfd92e3a556efdd1adfb84b34c75eb025843ea8bf0dd0"
      def install
        bin.install "tsync"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tsync -version")
  end
end
