# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webscreenshot < Formula
  desc "Tool to make screenshot of web pages from command line"
  homepage "https://fortio.org/"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortio/webscreenshot/releases/download/v0.3.0/webscreenshot_0.3.0_darwin_amd64.zip"
      sha256 "991b930ab88bd3bcd869498572dd47bd538cf80bfe349c8ebe6f6c7b654ab583"

      def install
        bin.install "webscreenshot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortio/webscreenshot/releases/download/v0.3.0/webscreenshot_0.3.0_darwin_arm64.zip"
      sha256 "63bfafa533ff492e8078249d629801613bde197ef909162c63952a8076555f4e"

      def install
        bin.install "webscreenshot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/webscreenshot/releases/download/v0.3.0/webscreenshot_0.3.0_linux_amd64.tar.gz"
      sha256 "fb3b52b6d6924ca9b9e9c86709f498fd22f082d2ac15fbf5fa0b2e13758ce895"
      def install
        bin.install "webscreenshot"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fortio/webscreenshot/releases/download/v0.3.0/webscreenshot_0.3.0_linux_arm64.tar.gz"
      sha256 "3a2369b76c4f83654033bfaa9eff7ea682eecd4b4769a9656fc885202d247dfb"
      def install
        bin.install "webscreenshot"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/webscreenshot -version")
  end
end
