# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Workflows < Formula
  desc ""
  homepage "https://fortio.org/"
  version "0.1.0-pre6"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/fortio/workflows/releases/download/v0.1.0-pre6/workflows_0.1.0-pre6_darwin_amd64.tar.gz"
      sha256 "dedc72b2f62289805dbe765e24b68cf7332012638e11f43be15709cc25079955"

      def install
        bin.install "workflows"
      end
    end
    on_arm do
      url "https://github.com/fortio/workflows/releases/download/v0.1.0-pre6/workflows_0.1.0-pre6_darwin_arm64.tar.gz"
      sha256 "c24e2993de2a224777bc91c59664b9244b09bac24a7a7bcd0831276df6a31d23"

      def install
        bin.install "workflows"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/workflows/releases/download/v0.1.0-pre6/workflows_0.1.0-pre6_linux_amd64.tar.gz"
        sha256 "3fbb1391f73db41747edafee8dd812bb6bc4f0f694236668bf60905586c880c2"

        def install
          bin.install "workflows"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fortio/workflows/releases/download/v0.1.0-pre6/workflows_0.1.0-pre6_linux_arm64.tar.gz"
        sha256 "5d9f6716f9acda3a7091020d42e3ef8f3458778373bb03a06a45d666a2bd3cb7"

        def install
          bin.install "workflows"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/workflows -version")
  end
end
